/*
 * Application.c
 *
 *  Created on: 23.06.2014
 *      Author: tastyger
 */

#include "Application.h"
#include "SM1.h"
#include "LED1.h"
#include "LED2.h"
#include "WAIT1.h"
#include "NSS.h"

#define SD1_SPI_WRITE_BLOCK_ENABLED 0
#define SD1_SPI_WRITE_READ_BLOCK_ENABLED 0

LDD_TDeviceData *SM1_DeviceData;

static volatile bool SD1_DataReceivedFlag = FALSE;
static volatile bool SD1_DataSentFlag = FALSE;

void APP_OnBlockSent(void) {
  SD1_DataSentFlag = TRUE;
}

void APP_OnBlockReceived(void) {
  SD1_DataReceivedFlag = TRUE;
}

void SD1_SPI_WRITE(unsigned char write) {
  unsigned char dummy;

  SD1_DataReceivedFlag = FALSE;
  (void)SM1_ReceiveBlock(SM1_DeviceData, &dummy, sizeof(dummy));
  (void)SM1_SendBlock(SM1_DeviceData, &write, sizeof(write));
  while(!SD1_DataReceivedFlag){}
}

#if SD1_SPI_WRITE_BLOCK_ENABLED
static void SD1_SPI_WRITE_BLOCK(unsigned char *writeP, uint16_t size) {
  unsigned char dummy[4];
  uint16_t writeSize;

  while(size>0) {
    if (size>sizeof(dummy)) {
      writeSize = sizeof(dummy);
    } else {
      writeSize = size;
    }
    SD1_DataReceivedFlag = FALSE;
    (void)SM1_ReceiveBlock(SM1_DeviceData, &dummy[0], writeSize);
    (void)SM1_SendBlock(SM1_DeviceData, writeP, writeSize);
    while(!SD1_DataReceivedFlag){}
    size -= writeSize;
    writeP += writeSize;
  }
}
#endif /* SD1_SPI_WRITE_BLOCK_ENABLED */

static void SD1_SPI_WRITE_READ(unsigned char write, unsigned char *readP) {
  SD1_DataReceivedFlag = FALSE;
  (void)SM1_ReceiveBlock(SM1_DeviceData, readP, 1);
  (void)SM1_SendBlock(SM1_DeviceData, &write, 1);
  while(!SD1_DataReceivedFlag){}
}

#if SD1_SPI_WRITE_READ_BLOCK_ENABLED
static void SD1_SPI_WRITE_READ_BLOCK(unsigned char *writeP, unsigned char *readP, uint16_t size) {
  SD1_DataReceivedFlag = FALSE;
  (void)SM1_ReceiveBlock(SM1_DeviceData, readP, size);
  (void)SM1_SendBlock(SM1_DeviceData, writeP, size);
  while(!SD1_DataReceivedFlag){}
}
#endif /* SD1_SPI_WRITE_READ_BLOCK_ENABLED */


#if SD1_SPI_WRITE_BLOCK_ENABLED || SD1_SPI_WRITE_READ_BLOCK_ENABLED
#define SPI_WRITE_READ_BLOCK_SIZE_DUMMY 512 /* 512 bytes of dummy values */
static const uint8_t dummyArr[SPI_WRITE_READ_BLOCK_SIZE_DUMMY] = {
  SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY,
  SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY,
  SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY,
  SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY,
  SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY,
  SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY, SD1_DUMMY
};
#endif

#define READ_BIT  (0<<7)
#define WRITE_BIT (1<<7)
#define DUMMY      0xFF
#define REG_LNA   0x0C /* LNA Settings */

static uint8_t data;

static void Test(void) {
  NSS_ClrVal();
  SD1_SPI_WRITE(READ_BIT|REG_LNA);
  SD1_SPI_WRITE_READ(DUMMY, &data);
  NSS_SetVal();
}

#include "spi.h"

uint16_t SpiInOut( Spi_t *obj, uint16_t outData ) {
  uint8_t data;

  SD1_SPI_WRITE(outData);
  SD1_SPI_WRITE_READ(DUMMY, &data);
  return data;
}

int App_main( void );

void APP_Run(void) {
  SM1_DeviceData = SM1_Init(NULL);
  LED1_Off();
  LED2_Off();
  for(;;) {
    //LED1_Neg();
    Test();
    //WAIT1_Waitms(500);
    App_main();
  }
}
